import type { ArcanistInput, ExternalBonuses } from '../calc/types';

/** A fresh account: no cards, no pet, nothing unlocked. */
export const FRESH_EXTERNAL: ExternalBonuses = {
  cards: {
    essence: { soft: 'none', dense: 'none', jagged: 'none' },
    rune: { ash: 'none', brine: 'none', chasm: 'none' },
    spell: {
      runicSurge: 'none',
      rainbowRift: 'none',
      manaflow: 'none',
      radiancy: 'none',
      prismism: 'none',
      veinboyant: 'none',
    },
    orb: {
      white: 'none',
      green: 'none',
      purple: 'none',
      orange: 'none',
      red: 'none',
      yellow: 'none',
    },
  },
  pets: {
    rhinoLevel: 0,
    rhinoSkin: false,
    rhinoQuestSkin: false,
    rhinoQuestLevel: 0,
    rhinoCard: 'none',
  },
  unlocks: {
    worldQuest25: false,
    worldQuest29: false,
    straightOuttaYanille: false,
    arcanistBundle: false,
    statueOfNatureGilded: false,
    w4GildedStatues: 0,
  },
  contractRuneCraftLevel: 0,
};

/** A freshly unlocked Arcanist: nothing bought, nothing unlocked. */
export const FRESH_INPUT: ArcanistInput = {
  essence: {
    essenceMine: 0,
    flatDamage1: 0,
    softMaxLoot: 0,
    shinyChance1: 0,
    critChance1: 0,
    flatDamage2: 0,
    denseMaxLoot: 0,
    armorPen: 0,
    superCrit1: 0,
    flatDamage3: 0,
    damagePct: 0,
    shinyLoot: 0,
    shinyChance2: 0,
    critChance2: 0,
    jaggedLoot: 0,
    regenRespawn: 0,
    superShinyChance1: 0,
    weakenNegate: 0,
    allMaxLoot: 0,
    damagePctBrittle: 0,
    superShinyLoot: 0,
    ultraCrit1: 0,
    critDamageAttackSpeed: 0,
    allMinLoot: 0,
    allDebuffNegate: 0,
    critRespawn: 0,
    superCritDaze: 0,
    ultraShiny: 0,
    allShinyLoot: 0,
    damagePctArmorPen: 0,
    superCritStun: 0,
    flatSuperCrit: 0,
    critDamageUltraCrit: 0,
    superShinyAttackSpeed: 0,
  },
  altars: {
    // The Ash Altar has no unlock cost on the sheet; it is available from the start.
    ash: { unlocked: true, active: false, capacity: 0, travel: 0, craft: 0 },
    brine: { unlocked: false, active: false, capacity: 0, travel: 0, craft: 0 },
    chasm: { unlocked: false, active: false, capacity: 0, travel: 0, craft: 0 },
  },
  spells: {
    runicSurge: { unlocked: false, level: 0, rank: 0 },
    rainbowRift: { unlocked: false, level: 0, rank: 0 },
    manaflow: { unlocked: false, level: 0, rank: 0 },
    radiancy: { unlocked: false, level: 0, rank: 0 },
    prismism: { unlocked: false, level: 0, rank: 0 },
    veinboyant: { unlocked: false, level: 0, rank: 0 },
  },
  exchange: {
    exchangeWizards: 0,
    exchangeTimer: 0,
    arcaneCardDamage: 0,
    rainbowFloorMulti: 0,
    lootbugBankedCap: 0,
    goldenPortalChance: 0,
    starSupergiantMulti: 0,
    wizardLootMulti: 0,
    geminiStarCap: 0,
    veinboyantUnlock: 0,
    prismaticFloorChance: 0,
    shinyFishMulti: 0,
    runeCraftMulti: 0,
    arcanistSpellPower: 0,
  },
  external: FRESH_EXTERNAL,
  // Soft is the only essence a fresh Arcanist can actually break.
  mining: 'soft',
};
