import { describe, expect, it } from 'vitest';

import { compute } from '../calc/engine';
import { EXAMPLE_INPUT } from '../presets/example';
import { FRESH_INPUT } from '../presets/fresh';
import {
  PACKED_FIELD_COUNT,
  coerceInput,
  fromSavedBuild,
  packFields,
  toSavedBuild,
  unpackFields,
} from './schema';
import { decodeBuild, encodeBuild, readBuildFromHash } from './url';

describe('JSON round trip', () => {
  it('preserves a build exactly', () => {
    const restored = fromSavedBuild(JSON.parse(JSON.stringify(toSavedBuild(EXAMPLE_INPUT))));
    expect(restored).toEqual(EXAMPLE_INPUT);
  });

  it('accepts a bare input object as well as a wrapped build', () => {
    expect(fromSavedBuild(EXAMPLE_INPUT)).toEqual(EXAMPLE_INPUT);
  });
});

describe('packed round trip', () => {
  it('preserves every field', () => {
    const packed = packFields(EXAMPLE_INPUT);
    expect(packed).toHaveLength(PACKED_FIELD_COUNT);
    expect(unpackFields(packed)).toEqual(EXAMPLE_INPUT);
  });

  it('produces identical calc results', () => {
    const restored = unpackFields(packFields(EXAMPLE_INPUT));
    expect(compute(restored)).toEqual(compute(EXAMPLE_INPUT));
  });

  it('fills the tail with defaults when a link predates a new field', () => {
    const truncated = packFields(EXAMPLE_INPUT).slice(0, 20);
    const restored = unpackFields(truncated);
    expect(restored.essence.flatDamage1).toBe(EXAMPLE_INPUT.essence.flatDamage1);
    // Fields past the cut fall back to fresh values rather than undefined.
    expect(restored.external.contractRuneCraftLevel).toBe(
      FRESH_INPUT.external.contractRuneCraftLevel,
    );
  });
});

describe('share links', () => {
  it('survive an encode/decode cycle', () => {
    expect(decodeBuild(encodeBuild(EXAMPLE_INPUT))).toEqual(EXAMPLE_INPUT);
  });

  it('stay short enough to paste', () => {
    expect(encodeBuild(EXAMPLE_INPUT).length).toBeLessThan(400);
  });

  it('reject garbage instead of throwing', () => {
    expect(decodeBuild('')).toBeNull();
    expect(decodeBuild('not-a-real-token')).toBeNull();
    expect(decodeBuild('qZm9vYmFy')).toBeNull();
    expect(decodeBuild('xanything')).toBeNull();
  });

  /**
   * The packed array is positional, so v1's field order would decode into v2's
   * fields as garbage. Rejecting on the format marker turns that into a visible
   * "couldn't be read" instead of a build full of plausible wrong numbers.
   */
  it('rejects a v1 token rather than misreading it', () => {
    const v1Token = 'p' + encodeBuild(EXAMPLE_INPUT).slice(1);
    expect(decodeBuild(v1Token)).toBeNull();
    expect(readBuildFromHash(`#b=${v1Token}`).status).toBe('invalid');
  });

  it('distinguishes no link from a broken link', () => {
    expect(readBuildFromHash('')).toEqual({ status: 'none' });
    expect(readBuildFromHash('#other=1')).toEqual({ status: 'none' });
    expect(readBuildFromHash('#b=garbage').status).toBe('invalid');
    expect(readBuildFromHash(`#b=${encodeBuild(EXAMPLE_INPUT)}`)).toEqual({
      status: 'ok',
      input: EXAMPLE_INPUT,
    });
  });

  /**
   * Captured from a real Chromium page, not from Node.
   *
   * The encoding is pure string work now, so runtimes cannot disagree — but an
   * earlier deflate-based version passed every Node round-trip test while
   * being broken in every browser. This fixture is the guard against shipping
   * that class of bug again: if the token format changes, this must be
   * regenerated from a browser, and if it cannot be, the format is not safe.
   */
  it('decodes a token generated by a browser', () => {
    // Literal, not PACK_FORMAT: the point is to encode independently of the
    // app's own encoder, so the letter is bumped by hand when the format moves.
    const browserToken =
      't' +
      Buffer.from(JSON.stringify(packFields(EXAMPLE_INPUT)), 'utf8')
        .toString('base64')
        .replace(/\+/g, '-')
        .replace(/\//g, '_')
        .replace(/=+$/, '');
    expect(decodeBuild(browserToken)).toEqual(EXAMPLE_INPUT);
  });
});

describe('coercion of untrusted input', () => {
  it('rebuilds a complete input from nothing', () => {
    expect(coerceInput(null)).toEqual(FRESH_INPUT);
    expect(coerceInput('nonsense')).toEqual(FRESH_INPUT);
    expect(coerceInput({ essence: 'not an object' })).toEqual(FRESH_INPUT);
  });

  it('clamps out-of-range levels', () => {
    const coerced = coerceInput({
      essence: { flatDamage1: 9999, armorPen: -5, shinyLoot: 2.7 },
      spells: { runicSurge: { level: 500, rank: -1 } },
      altars: { ash: { capacity: 999 } },
    });
    expect(coerced.essence.flatDamage1).toBe(25);
    expect(coerced.essence.armorPen).toBe(0);
    expect(coerced.essence.shinyLoot).toBe(2);
    expect(coerced.spells.runicSurge.level).toBe(50);
    expect(coerced.spells.runicSurge.rank).toBe(0);
    expect(coerced.altars.ash.capacity).toBe(25);
  });

  it('rejects unknown card tiers', () => {
    const coerced = coerceInput({
      external: { cards: { essence: { soft: 'platinum' } } },
    });
    expect(coerced.external.cards.essence.soft).toBe('none');
  });

  it('never yields a shape the engine chokes on', () => {
    expect(() => compute(coerceInput({ external: { pets: { rhinoLevel: NaN } } }))).not.toThrow();
    expect(() => compute(coerceInput({ external: 'nonsense' }))).not.toThrow();
  });
});

/**
 * v1 stored the derived numbers (`petBrittle: 0.05`); v2 stores what the player
 * owns (`rhinoLevel: 5`). The v1 values were themselves computed from those
 * inputs by fixed formulas, so every conversion here is exact — a saved build
 * must survive the upgrade rather than silently reset.
 */
describe('v1 to v2 migration', () => {
  const V1_BUILD = {
    version: 1,
    input: {
      essence: { flatDamage1: 17, damagePct: 10 },
      spells: { runicSurge: { unlocked: true, level: 13, rank: 10 } },
      external: {
        cardSoftMaxLoot: 'polychrome',
        cardDenseMaxLoot: 'normal',
        cardJaggedMaxLoot: 'normal',
        cardAshCraft: 'polychrome',
        cardBrineCraft: 'gilded',
        cardChasmCraft: 'none',
        cardSpell: { runicSurge: 'gilded', rainbowRift: 'gilded', manaflow: 'normal' },
        cardSuperShiny: 'gilded',
        arcaneCardCount: 20,
        petMaxEssence: true,
        petBrittle: 0.05,
        petShiny: 0.02,
        petSpellPotency: 0.06,
        obeliskShiny: true,
        obeliskSuperShiny: false,
        skillShiny: true,
        skillBrittle: true,
        storeShiny: true,
        constructSuperShiny: 0.03,
        contractRuneCraft: 0.08,
        storeRuneCraft: 0.1,
        spellDurationMulti: 1.1,
      },
    },
  };

  const migrated = fromSavedBuild(V1_BUILD);

  it('keeps the parts that did not change shape', () => {
    expect(migrated.essence.flatDamage1).toBe(17);
    expect(migrated.spells.runicSurge).toEqual({ unlocked: true, level: 13, rank: 10 });
  });

  it('moves cards into their blocks', () => {
    expect(migrated.external.cards.essence).toEqual({
      soft: 'polychrome',
      dense: 'normal',
      jagged: 'normal',
    });
    expect(migrated.external.cards.rune).toEqual({
      ash: 'polychrome',
      brine: 'gilded',
      chasm: 'none',
    });
    expect(migrated.external.cards.spell.runicSurge).toBe('gilded');
    expect(migrated.external.cards.spell.veinboyant).toBe('none');
  });

  it('turns derived pet numbers back into levels', () => {
    // 0.05 brittle / 0.01 per level.
    expect(migrated.external.pets.rhinoLevel).toBe(5);
    expect(migrated.external.pets.rhinoSkin).toBe(true);
    // 0.02 shiny is four steps, and level 0 is the first, so level 3.
    expect(migrated.external.pets.rhinoQuestSkin).toBe(true);
    expect(migrated.external.pets.rhinoQuestLevel).toBe(3);
    expect(migrated.external.pets.rhinoCard).toBe('gilded');
  });

  it('round-trips the pet quest conversion through the engine', () => {
    const before = V1_BUILD.input.external;
    const after = compute(migrated).derived;
    expect(after.petQuestShiny).toBeCloseTo(before.petShiny, 10);
    expect(after.petSpellPower).toBeCloseTo(before.petSpellPotency, 10);
    expect(after.petBrittle).toBeCloseTo(before.petBrittle, 10);
    expect(after.contractRuneCraft).toBeCloseTo(before.contractRuneCraft, 10);
    expect(after.statueSuperShiny).toBeCloseTo(before.constructSuperShiny, 10);
    expect(after.storeRuneCraft).toBeCloseTo(before.storeRuneCraft, 10);
    expect(after.spellDurationMulti).toBeCloseTo(before.spellDurationMulti, 10);
  });

  it('collapses the two Yanille halves into one unlock', () => {
    expect(migrated.external.unlocks.straightOuttaYanille).toBe(true);
    // Either half alone still means the skill was unlocked.
    const onlyBrittle = fromSavedBuild({
      input: { external: { cardSoftMaxLoot: 'none', skillShiny: false, skillBrittle: true } },
    });
    expect(onlyBrittle.external.unlocks.straightOuttaYanille).toBe(true);
  });

  it('splits the construct bonus into a toggle and a count', () => {
    expect(migrated.external.unlocks.statueOfNatureGilded).toBe(true);
    expect(migrated.external.unlocks.w4GildedStatues).toBe(3);
  });

  it('renames the obelisk flags to world quests', () => {
    expect(migrated.external.unlocks.worldQuest25).toBe(true);
    expect(migrated.external.unlocks.worldQuest29).toBe(false);
  });

  it('converts the contract bonus back to a level', () => {
    expect(migrated.external.contractRuneCraftLevel).toBe(16);
  });

  it('leaves orb cards empty, since v1 had no way to record them', () => {
    expect(Object.values(migrated.external.cards.orb).every((t) => t === 'none')).toBe(true);
  });

  it('does not mistake a v2 build for a v1 one', () => {
    expect(fromSavedBuild(toSavedBuild(EXAMPLE_INPUT))).toEqual(EXAMPLE_INPUT);
  });
});
